//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.FacadeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonComplete", Namespace="http://schemas.datacontract.org/2004/07/ServerFacade")]
    [System.SerializableAttribute()]
    public partial class PersonComplete : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacadeServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompleteData", ReplyAction="http://tempuri.org/IService1/GetCompleteDataResponse")]
        Client.FacadeServiceReference.PersonComplete[] GetCompleteData();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetCompleteData", ReplyAction="http://tempuri.org/IService1/GetCompleteDataResponse")]
        System.IAsyncResult BeginGetCompleteData(System.AsyncCallback callback, object asyncState);
        
        Client.FacadeServiceReference.PersonComplete[] EndGetCompleteData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DoSocialism", ReplyAction="http://tempuri.org/IService1/DoSocialismResponse")]
        int DoSocialism();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DoSocialism", ReplyAction="http://tempuri.org/IService1/DoSocialismResponse")]
        System.IAsyncResult BeginDoSocialism(System.AsyncCallback callback, object asyncState);
        
        int EndDoSocialism(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.FacadeServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCompleteDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCompleteDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.FacadeServiceReference.PersonComplete[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.FacadeServiceReference.PersonComplete[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoSocialismCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DoSocialismCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.FacadeServiceReference.IService1>, Client.FacadeServiceReference.IService1 {
        
        private BeginOperationDelegate onBeginGetCompleteDataDelegate;
        
        private EndOperationDelegate onEndGetCompleteDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetCompleteDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginDoSocialismDelegate;
        
        private EndOperationDelegate onEndDoSocialismDelegate;
        
        private System.Threading.SendOrPostCallback onDoSocialismCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetCompleteDataCompletedEventArgs> GetCompleteDataCompleted;
        
        public event System.EventHandler<DoSocialismCompletedEventArgs> DoSocialismCompleted;
        
        public Client.FacadeServiceReference.PersonComplete[] GetCompleteData() {
            return base.Channel.GetCompleteData();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCompleteData(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCompleteData(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client.FacadeServiceReference.PersonComplete[] EndGetCompleteData(System.IAsyncResult result) {
            return base.Channel.EndGetCompleteData(result);
        }
        
        private System.IAsyncResult OnBeginGetCompleteData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetCompleteData(callback, asyncState);
        }
        
        private object[] OnEndGetCompleteData(System.IAsyncResult result) {
            Client.FacadeServiceReference.PersonComplete[] retVal = this.EndGetCompleteData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCompleteDataCompleted(object state) {
            if ((this.GetCompleteDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCompleteDataCompleted(this, new GetCompleteDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCompleteDataAsync() {
            this.GetCompleteDataAsync(null);
        }
        
        public void GetCompleteDataAsync(object userState) {
            if ((this.onBeginGetCompleteDataDelegate == null)) {
                this.onBeginGetCompleteDataDelegate = new BeginOperationDelegate(this.OnBeginGetCompleteData);
            }
            if ((this.onEndGetCompleteDataDelegate == null)) {
                this.onEndGetCompleteDataDelegate = new EndOperationDelegate(this.OnEndGetCompleteData);
            }
            if ((this.onGetCompleteDataCompletedDelegate == null)) {
                this.onGetCompleteDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCompleteDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetCompleteDataDelegate, null, this.onEndGetCompleteDataDelegate, this.onGetCompleteDataCompletedDelegate, userState);
        }
        
        public int DoSocialism() {
            return base.Channel.DoSocialism();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDoSocialism(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoSocialism(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndDoSocialism(System.IAsyncResult result) {
            return base.Channel.EndDoSocialism(result);
        }
        
        private System.IAsyncResult OnBeginDoSocialism(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDoSocialism(callback, asyncState);
        }
        
        private object[] OnEndDoSocialism(System.IAsyncResult result) {
            int retVal = this.EndDoSocialism(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDoSocialismCompleted(object state) {
            if ((this.DoSocialismCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoSocialismCompleted(this, new DoSocialismCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoSocialismAsync() {
            this.DoSocialismAsync(null);
        }
        
        public void DoSocialismAsync(object userState) {
            if ((this.onBeginDoSocialismDelegate == null)) {
                this.onBeginDoSocialismDelegate = new BeginOperationDelegate(this.OnBeginDoSocialism);
            }
            if ((this.onEndDoSocialismDelegate == null)) {
                this.onEndDoSocialismDelegate = new EndOperationDelegate(this.OnEndDoSocialism);
            }
            if ((this.onDoSocialismCompletedDelegate == null)) {
                this.onDoSocialismCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoSocialismCompleted);
            }
            base.InvokeAsync(this.onBeginDoSocialismDelegate, null, this.onEndDoSocialismDelegate, this.onDoSocialismCompletedDelegate, userState);
        }
    }
}
